### ISSUE TITLE
where is the EventBusLoggerFlipperPlugin?

### ISSUE THREAD

**Issue by hss01248** [SaqibJDev/EventBusLogger-Flipper#5]
just a Readme here?

**Comment by SaqibJDev** [comment]
Hi @hss01248,
Did you mean the Android part? I'll push it today with adaptation.

**Comment by SaqibJDev** [comment]
@hss01248  Sorry, it took a bit longer. here is the plugin directory
https://github.com/SaqibJDev/EventBusLogger-Flipper/tree/main/sample/Android/app/src/main/java/com/flipper/evenbuslogger/sample/eventbus/flipper
